SELECT * From car_categorical;

INSERT INTO car_categorical (maxe, brand, model) VALUES
(1, 'Toyota', 'Vios'),
(2, 'Toyota', 'Camry'),
(3, 'Toyota', 'Fortuner'),
(4, 'Toyota', 'Corolla Altis'),
(5, 'Toyota', 'Hilux'),
(6, 'Toyota', 'Innova'),
(7, 'Honda', 'Civic'),
(8, 'Honda', 'CR-V'),
(9, 'Honda', 'City'),
(10, 'Honda', 'HR-V'),
(11, 'Honda', 'Brio'),
(12, 'Ford', 'Ranger'),
(13, 'Ford', 'Everest'),
(14, 'Ford', 'EcoSport'),
(15, 'Ford', 'Focus'),
(16, 'Hyundai', 'Accent'),
(17, 'Hyundai', 'Tucson'),
(18, 'Hyundai', 'SantaFe'),
(19, 'Hyundai', 'Elantra'),
(20, 'Hyundai', 'Kona'),
(21, 'Kia', 'Morning'),
(22, 'Kia', 'Seltos'),
(23, 'Kia', 'Sorento'),
(24, 'Kia', 'Cerato'),
(25, 'Kia', 'Carnival'),
(26, 'Mazda', 'CX-5'),
(27, 'Mazda', '3'),
(28, 'Mazda', '6'),
(29, 'Mazda', 'BT-50'),
(30, 'Mitsubishi', 'Xpander'),
(31, 'Mitsubishi', 'Outlander'),
(32, 'Mitsubishi', 'Attrage'),
(33, 'Mitsubishi', 'Triton'),
(34, 'VinFast', 'Fadil'),
(35, 'VinFast', 'Lux A2.0'),
(36, 'VinFast', 'Lux SA2.0'),
(37, 'VinFast', 'President'),
(38, 'Chevrolet', 'Spark'),
(39, 'Chevrolet', 'Cruze'),
(40, 'Chevrolet', 'Captiva'),
(41, 'Chevrolet', 'Colorado'),
(42, 'Nissan', 'Sunny'),
(43, 'Nissan', 'Navara'),
(44, 'Nissan', 'X-Trail');

SELECT * FROM CAR_CATEGORICAL